version: "3.7"

volumes:
  mongo:

services:
  mongodb:
    build: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
